version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/venv  
    environment:
      - DEBUG=1
      - DOCKER_ENV=1
      - DJANGO_SECRET_KEY={DJANGO_SECRET_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - URL=${URL}
      - POSTGRES_DB=contractor_generator
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=contractor_generator
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data:
